#3)
print("Era uma vez, um mundo em trevaz, infestado de monstros pelos céus e pela terra...")
espera = input()
print("Nesse mesmo mundo, um certo dia no meio de todo o desespero, surgiu um goblim com uma espada, seu nome era ...")
espera = input()
print("'FREDERICK!'")
espera = input()
print("'Está tudo bem, Tereza...'")
espera = input()
print("'Oh, Frederick...'")
espera = input()
print("'Vamos para casa, Tereza'")